### ISSUE TITLE
Free with Prime compatibility

### ISSUE THREAD

**Issue by ChobitsCrazy** [FreeStuffBot/FreeStuff#37]
Hey love this app and my community is really racking up the games. Most of us have Amazon Prime and they often run free games as well that we aren't notified for. Would it be possible to add integration for Free Games with Prime?

Thanks!

**Comment by cavazoshj** [comment]
Yes, please. A lot of very good titles come through Amazon games and would be great to get this added.

**Comment by l0g4n1337** [comment]
Please!

**Comment by maanex** [comment]
This is currently being built and will hopefully ship soon. We'll keep you updated on our Discord server.
I am closing this issue early because we are not planning to keep using GitHub Issues in the future.
