### ISSUE TITLE
More Currency Support

### ISSUE THREAD

**Issue by garv-shah** [FreeStuffBot/FreeStuff#39]
**Is your feature request related to a problem? Please describe.**
The bot's selection for currencies is quite limited, for example, I would use AUD, but the bot does not seem to support that

**Describe the solution you'd like**
A more comprehensive list of alternative currencies in settings

**Describe alternatives you've considered**
Could possibly use a currency conversion API, there would be plenty out there

Besides that, love the bot, thank you so much for maintaining it!

**Comment by maanex** [comment]
Hey there, thanks for your feature request! We are already using currency conversion APIs for most of our currencies. As this is a feature request and not a bug report please post a suggestion in our [Discord Server](https://discord.gg/Dr7hGv3Y) or upvote one there if this has already been suggested. This way we can keep track of feature requests in one place and actually see which ones the users like to see the most.
We'd like to limit GH issues to actual bugs or technical matters, though this should probably be communicated better.
