### ISSUE TITLE
The bot stopped posting messages saying the games are free

### ISSUE THREAD

**Issue by ReiDaTecnologia** [FreeStuffBot/FreeStuff#45]
**Describe the bug**
It was working for a while but then, suddenly it stopped posting message saying games are free even tho there is actually free games available like from Epic Games (Example: Saints Row IV: Re-Elected).

**To Reproduce**
1. Use command '...'
2. Change bot's permissions to '....'
3. Type '....' in chat

**Expected behavior**
The bot post a message saying games are free when they become free mainly before the time runs out.

**Screenshots**

**Additional context**

**Comment by maanex** [comment]
Please contact support if you are having configuration issues.
