### ISSUE TITLE
Forum posts

### ISSUE THREAD

**Issue by Duckrinium** [FreeStuffBot/FreeStuff#47]
**Is your feature request related to a problem? Please describe.**
I have a forum channel for free stuff people share with each other, bot cannot create posts.

**Describe the solution you'd like**
It would be nice if bot could create a forum channel with all the platform and store tags and all that and post there instead, or use already existing ones (probably will need to assign tags yourself)

**Describe alternatives you've considered**
Creating post and using switching it to post there, not ideally but works...

**Additional context**
Maybe scheduling a lock, I don't know?
![Screenshot_20221228_185537](https://user-images.githubusercontent.com/37019004/209838579-c1ef87d3-b3dc-4d8a-afdd-dae04e1f50e1.png)

**Comment by maanex** [comment]
Thanks for your feature request! The general ability to make the bot use forums is being worked on, though not ready for release yet. Tags are an interesting suggestion, we'll keep that in mind.
Please use our suggestions channel on Discord (https://discord.gg/freestuff-517009303203479572) for future feature requests, to keep things organized 👍
